### ISSUE TITLE
Give a fuck about the module name

### ISSUE THREAD

**Issue by ivan-m** [Akii/acme-fucks#4]
In `acme-fucks.cabal`, you have:

```
exposed-modules: Data.Monoid.Fucks
```

The source file itself is found in just `Fucks.hs` (no containing directory within the stated `hs-source-dirs`).

The module header states that it is `Acme.Fucks` (which means it should really be in `Acme/Fucks.hs`, not just `Fucks.hs`).

**Comment by Akii** [comment]
Thank you for this bug report!

If the guy who merged the PRs would give fucks (especially the "testing-fucks" variant) this would not have happened!

Someone should accumulate enough fucks to make an automatic build happening :D

I will try to fix this asap

**Comment by Akii** [comment]
Just unfucked the project with f637fdf8c5619a73af8e956c4628911a18cdbec7.

**Comment by ivan-m** [comment]
That seems to do it.
