### ISSUE TITLE
Only export Fucks type, not constructor

### ISSUE THREAD

**Issue by TimoFreiberg** [Akii/acme-fucks#6]
This would disable creating `Fucks` values with `n /= 0` (which clearly makes no sense).

The only way to create a `Fucks` value would be via `mempty`.

A more descriptive alias for `mempty` could be implemented, like `giveNoFucks` or similar.

**Comment by Akii** [comment]
Yes, we must not allow giving fucks. I'll look into it as soon as I accumulated enough fucks to fix (probably this evening).

**Comment by treeowl** [comment]
I disagree. There's no reason to give a fuck about invariant violation.

**Comment by Akii** [comment]
Got a point there. Especially when you work with Fucks you'll always end up with the right amounts of Fucks to give.

**Comment by Akii** [comment]
We really should protect the library users from extracting the number out of Fucks though. Just imagine if someone would pattern match and misuse the type. We could of course also not give a fuck about that. Difficult thing.

**Comment by TimoFreiberg** [comment]
Its a design decision between not giving a fuck about laws and having the Fucks type correctly represent "no Fucks" at all times.
The first is more laissez-faire, the second is more hardcore anarchist. I leave the decision to the benevolent dictator for life of the library

**Comment by Akii** [comment]
I propose the following way of acquiring Fucks:

```
type Amount = Int

giveFucks :: Amount -> Maybe (Fucks f)
giveFucks 0 = Just mempty
giveFucks _ = Nothing
```

**Comment by Akii** [comment]
Alternatively we could also not give a fuck about exceptions (=

**Comment by Akii** [comment]
Went with that approach now.

**Comment by Akii** [comment]
Fixed in lib.
