### ISSUE TITLE
Don't give a fuck about monads

### ISSUE THREAD

**Issue by treeowl** [Akii/acme-fucks#7]
What's wrong with this?

```haskell
instance Monad Fucks where
   _ >>= _ = mempty
```

I also recommend that you not give a fuck about whether it works for older versions of GHC, so you shouldn't include a definition of `return`.

**Comment by Akii** [comment]
Oh I like that!

**Comment by Akii** [comment]
Gave enough fucks to fix!

**Comment by Akii** [comment]
Closin' that for now.
